### ISSUE TITLE
mdb_txn_commit: MDB_MAP_FULL: Environment mapsize limit reached

### ISSUE THREAD

**Issue by SirKawaii** [cleve/pulzar#5]
after days of using and with a bunch of request at the same time , the service start to fail with this error:

lmdb.MapFullError: mdb_txn_commit: MDB_MAP_FULL: Environment mapsize limit reached
2021-01-07 14:18:31,652:ERROR::PutProcess:mdb_txn_commit: MDB_MAP_FULL: Environment mapsize limit reached
Traceback (most recent call last):
  File "./volume/put_process.py", line 74, in notify_record_to_master
    self.db_backup.put_value(
  File "./pulzarcore/core_db.py", line 52, in put_value
    return True

this could failed by the default map_size value, that is very low by default .
https://lmdb.readthedocs.io/en/release/#lmdb.lmdb.open

**Comment by cleve** [comment]
Fixed

- Size increased to 10GB
