### ISSUE TITLE
OSError: [Errno 28] No space left on device: '/tmp/

### ISSUE THREAD

**Issue by SirKawaii** [cleve/pulzar#7]
After 2 weeks of use the /tmp folder in the main container is full raising the following error:

`OSError: [Errno 28] No space left on device: '/tmp/tmpi05aazi6'
Traceback (most recent call last):
  File "varidb.py", line 9, in application
    return master.process_request(env, start_response)
  File "./master/master.py", line 23, in process_request
    message = self.dispatcher.classify_request(
  File "./master/dispatcher.py", line 113, in classify_request
    return extension.process_request(
  File "./master/extension_process.py", line 58, in process_request
    file_path = self.read_binary_file(env, url_path)
  File "./master/extension_process.py", line 43, in read_binary_file
    temp_file = self.utils.get_tmp_file()
  File "./pulzarutils/utils.py", line 246, in get_tmp_file
    return tempfile.NamedTemporaryFile(delete=False)
  File "/usr/lib/python3.8/tempfile.py", line 680, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.8/tempfile.py", line 389, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)`

one solution could be restart the container every x days to prevent this behavior.

**Comment by cleve** [comment]
Confirmed, the extension imagematching is not cleaning the temporal files

**Comment by cleve** [comment]
The issue was fixed. Also, new integration tests were created
